version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mtg_cards_db
    environment:
      POSTGRES_DB: mtg_cards
      POSTGRES_USER: mtg_user
      POSTGRES_PASSWORD: mtg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: mtg_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: